version: '3'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGDBNAME=postgres
    volumes:
      - .:/app
    networks:
      - gorestapi
  db:
    restart: always
    image: postgres
    networks:
      - gorestapi

networks:
  gorestapi:
