version: '3'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PGPASSWORD=password
      - PGHOST=db
    networks:
      - gorestapi
  db:
    restart: always
    image: postgres
    networks:
      - gorestapi

networks:
  gorestapi:
