version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PGPASSWORD=postgres
      - PGHOST=db
      - PGUSER=postgres
      - PGDBNAME=postgres
      - PASSPHRASE=yetanotherbucketlistapp
    volumes:
      - .:/app
    networks:
      - gorestapi
  db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "8093:5432"
    networks:
      - gorestapi

networks:
  gorestapi:
