apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8bucketapi.fullname" . }}
  labels:
{{ include "k8bucketapi.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8bucketapi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8bucketapi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ include "k8bucketapi.fullname" . }}
          image: samuelvarejames/go_bucketlist_api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.k8application.serverPort }}
            httpGet:
              path: /
              port: {{ .Values.k8application.serverPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.k8application.serverPort }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: PGHOST
              value: {{ .Release.Name }}-postgresql.default.svc.cluster.local
            - name: PGUSER
              value: postgres
            - name: PGDBNAME
              value: postgres
            - name: PASSPHRASE
              value: yetanotherbucketlistapp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
